### ISSUE TITLE
PV hidden when going forward/back on positions

### ISSUE THREAD

**Issue by roy7** [gcp/leela-zero#651]
I was analyzing a game, and so this is basically what I did, with no playout cap.

loadsgf newwin.sgf 210

genmove w

which wasn't the move I'm interested in. It did a little search on the move I cared about, but not much. So I then:

undo
play w s4
genmove b

So it does lots of search after white moved to S4 (the move I'm interested in). So I'm curious now how the search results would be when it has lots of "after S4" info in the tree. So i:

undo
undo
genmove w

And the search results take this format:

Thinking at most 49.3 seconds...
NN eval=0.023561
Playouts: 5641, Win:  3.51%, PV: S4
Playouts: 12037, Win:  3.88%, PV: S4
Playouts: 18084, Win:  3.94%, PV: S4
Playouts: 23731, Win:  3.83%, PV: S4
Playouts: 29361, Win:  3.77%, PV: S4
Playouts: 35370, Win:  3.68%, PV: S4
Playouts: 41455, Win:  3.65%, PV: S4
Playouts: 47537, Win:  3.70%, PV: S4
Playouts: 53339, Win:  3.61%, PV: S4
Playouts: 58827, Win:  3.64%, PV: S4
Playouts: 64845, Win:  3.57%, PV: S4
Playouts: 71111, Win:  3.49%, PV: S4
Playouts: 77304, Win:  3.48%, PV: S4
Playouts: 83222, Win:  3.48%, PV: S4
Playouts: 88419, Win:  3.42%, PV: S4
Playouts: 94776, Win:  3.42%, PV: S4
Playouts: 100187, Win:  3.42%, PV: S4
Playouts: 106412, Win:  3.35%, PV: S4
Playouts: 112614, Win:  3.35%, PV: S4

  S4 ->  140459 (V:  2.81%) (N:  0.91%) PV: S4
 B19 ->   38659 (V:  3.49%) (N:  2.40%) PV: B19 C19 G5 D5 A15 A17 A16 A19 A17 B19 D8 D7
 A15 ->   34313 (V:  2.49%) (N: 67.55%) PV: A15 S4 T4 T5 S5

Etc.

I don't know if it's a side of effect of something to do with the TTable or another tree re-use optimization/feature, but I'm guessing the reason no variations for S4 appear is that those various were already explored in the tree previously. Although it seems odd to me they never appear even when the final move is selected.

Might it be because S4 has tons of search (from my searching there after S4 was chosen) but S4 isn't actually the best move and has a lower V %, so all new search is going into other moves? And maybe if 0 playouts went into S4, S4's PV can't expand for display? 

This is on the winogard branch, so I tried on the /next branch with same result.

I tried using --visits 50000 which was interesting. After the undo undo step (over 50K visits in the total tree if all that tree history is being stored), doing the genmove instantly moves with:

genmove w
Thinking at most 49.8 seconds...
NN eval=0.089789

 A15 ->    6944 (V:  1.86%) (N: 73.66%) PV: A15
  D5 ->    6811 (V:  3.85%) (N:  2.54%) PV: D5
50003 visits, 480 nodes, 2 playouts, 10 n/s

= A15

To be sure the S4 data I forced it to explore was still in there, I did:

undo
play w s4
genmove b

With an instant result:

Thinking at most 49.5 seconds...
NN eval=0.982375

 A15 ->   31669 (V: 97.53%) (N: 35.50%) PV: A15
  K1 ->     159 (V: 95.34%) (N:  6.61%) PV: K1
50003 visits, 476 nodes, 2 playouts, 18 n/s

= A15

So at the time my "genmove w" gave me an instant A15 move, 50000+ visits did exist in the S4 branch but S4 wasn't the move chosen (and that move didn't appear in the printout, only A15 and D5 did which were the two highest "normally" but all the rest didn't show).

**Comment by roy7** [comment]
I'm guessing these oddities will happen until an alternate tree re-use is implemented such as https://github.com/gcp/leela-zero/pull/632, or some sort of ttable_sync_all_children function gets added?

**Comment by gcp** [comment]
ttable_sync_children should probably be done when printing the PV (chess engines do it too, and the issue reported here is the reason why)

**Comment by roy7** [comment]
@gcp It'd also be needed for dump_training, not just dump_stats, right?

**Comment by gcp** [comment]
Not really. The problem is the tree after the hash hit is never explored. That can't happen at the root. (It can choose to not explore some moves it did before, but that's entirely unrelated from this problem)

**Comment by roy7** [comment]
Ah ok. I was thinking this and https://github.com/gcp/leela-zero/pull/581 were two sides of the same coin.

**Comment by killerducky** [comment]
@roy7 I'll be looking into these types of issues after #632 and #645 are resolved.

**Comment by gcp** [comment]
#632 will solve the forward case, but not the backward case.

**Comment by roy7** [comment]
Well the forward case is the more important one since that impact actual bot play. The backwards case is just for people who move around in the history to do post-game analysis. I'm glad that is resolved. :D I've gone ahead and updated RoyalZero to the latest /next code and latest network.

**Comment by killerducky** [comment]
bump @roy7 I think these problems should be resolved now.

**Comment by roy7** [comment]
@killerducky I'll test it in next day or two. :)

**Comment by roy7** [comment]
@killerducky Hmm. I think I still have an oddity with this.

I tried to reduplicate what I did before. I make 21K search at T4, go back and force S4 and search 34K to A15 (so now S4 A15 has 34K search), I undo twice and search again and S4 is at 883 total visits. So the tree under S4 A15 is missing although S4 A15 is the main variation under S4 in the search results at that point.

```text
genmove w
Thinking at most 50.0 seconds...
NN eval=0.037356
Playouts: 842, Win:  2.38%, PV: A15 S4 T4 T5 S5 T3 S3 S6 T2 T1 G5 G4 D5 E5
Playouts: 1754, Win:  2.79%, PV: A15 S4 T4 T5 S5 T3 S3 S6 T2 T1 G5 G4 D5 E5 D8 D7
Playouts: 2728, Win:  3.16%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12
Playouts: 3847, Win:  3.32%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12
Playouts: 4930, Win:  3.39%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12
Playouts: 6189, Win:  3.49%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12
Playouts: 7842, Win:  3.60%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 G6 F6
Playouts: 9594, Win:  3.65%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 G6 F6
Playouts: 10891, Win:  3.69%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 G6 F6
Playouts: 12267, Win:  3.72%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 G6 F6
Playouts: 13796, Win:  3.78%, PV: T4 A15 B15 C8 B8 D8 D5 E5 G5 G4 A16 B19 Q13 H4 Q12 P9 G6 F6 O19 Q19
Playouts: 15134, Win:  3.81%, PV: T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 G6 F6
Playouts: 16688, Win:  3.86%, PV: T4 A15 B15 C8 B8 D8 D5 E5 G5 G4 A16 B19 Q13 H4 Q12 P9 G6 F6 O19 Q19
Playouts: 18045, Win:  3.88%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8
Playouts: 19400, Win:  3.88%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8 A19
Playouts: 20754, Win:  3.88%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5
Playouts: 22142, Win:  3.89%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8 A19
Playouts: 23473, Win:  3.91%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8 A19
Playouts: 25221, Win:  3.95%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8 A19

  T4 ->   21264 (V:  4.40%) (N:  1.71%) PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
 A15 ->    2322 (V:  0.97%) (N: 61.42%) PV: A15 S4 T4 T5 S5 T3 S3 S6 T2 T1 G5 G4 D5 E5 D8 D7 C8
  S4 ->     631 (V:  4.11%) (N:  1.33%) PV: S4 A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13
  S3 ->     466 (V:  4.36%) (N:  0.18%) PV: S3 A15 B15 C8 B8 D8 D5 E5 G5 G4 G6 H4 A16 B19 O19
  D5 ->     218 (V:  2.63%) (N:  2.98%) PV: D5 E5 A15 S4 T4 T5 G5 G4 O19 Q19 D8 D7 C8 H4 G6 F6
  G5 ->     179 (V:  2.05%) (N:  3.27%) PV: G5 S4 T4 T5 A15 D5 G4 F4 H4 J4 G6 F6 C8
  C8 ->     161 (V:  2.18%) (N:  2.77%) PV: C8 A15 B15 S4 T4 T5 S5 S6 A16 B19 G5
 O19 ->     133 (V:  2.08%) (N:  2.40%) PV: O19 A15 B15 S4 T4 T5 S5 S6 A16 B19 D5 E5 G5 G4
  H4 ->     130 (V:  2.58%) (N:  1.82%) PV: H4 S4 T4 T5 A15 A17 A16 C8 B8 D8 D5 E5 O19
 B19 ->     104 (V:  2.17%) (N:  1.80%) PV: B19 C19 A15 S4 T4 T5 A17 A19 S5 T3 B19 C8 B8 D8
 Q13 ->      94 (V:  2.10%) (N:  1.67%) PV: Q13 A15 A16 B15 C15 B19 Q12 P9 D5 E5 G5
  D8 ->      87 (V:  2.75%) (N:  1.13%) PV: D8 A15 B15 S4 T4 T5 S5 T3 S3
 Q19 ->      79 (V:  2.35%) (N:  1.25%) PV: Q19 R19 A15 S4 T4 T5 S5 S6 P19 C8 B8
  G6 ->      68 (V:  2.53%) (N:  0.99%) PV: G6 A15 B15 S4 T4 T5 S5 T3 S3 S6 T2
 S16 ->      60 (V:  3.12%) (N:  0.61%) PV: S16 S17 T16 T17 A15 S4 T4 T5 S5 S6 Q19 R19
  D7 ->      54 (V:  2.57%) (N:  0.77%) PV: D7 S4 T4 T5 A15 D5 D8 G5 G6 H4 F6 E5
 P19 ->      51 (V:  2.52%) (N:  0.73%) PV: P19 A15 Q19 R19 B15 S4 T4 T5 S5 T3 S3
  G4 ->      46 (V:  3.69%) (N:  0.25%) PV: G4 H4 G5 F4 A15 S4 T4 T5 S5 T3 S3 S6
  E5 ->      44 (V:  3.51%) (N:  0.31%) PV: E5 D5 G5 F6 A15 S4 T4 T5 S5 T3 S3
  F6 ->      32 (V:  3.62%) (N:  0.18%) PV: F6 G6 G5 F6 A15 S4 T4 T5 S5
 A17 ->      32 (V:  3.37%) (N:  0.23%) PV: A17 A15 B15 B19 A19 S4 T4 T5
 A19 ->      29 (V:  3.28%) (N:  0.24%) PV: A19 A15 B15 B19 A17 S4 T4 T5 S5
 Q12 ->      24 (V:  3.26%) (N:  0.19%) PV: Q12 A15 Q13 P9 B15 S4 T4 T5 S5 S6
 N19 ->      20 (V:  2.96%) (N:  0.23%) PV: N19 A15 B15 S4 T4 T5
  T3 ->      19 (V:  3.03%) (N:  0.19%) PV: T3 A15 B15 S4 T4 T5 S5 S6
  K1 ->      18 (V:  2.63%) (N:  0.23%) PV: K1 L1 A15 S4 T4 T5 S5 T3 S3 S6
  C5 ->      15 (V:  2.76%) (N:  0.20%) PV: C5 A15 B15 S4 T4 T5 S5 T3
  H8 ->      15 (V:  2.06%) (N:  0.27%) PV: H8 S4 T4 T5 S5 S6 A15
 B15 ->      13 (V:  2.44%) (N:  0.19%) PV: B15 S4 T4 T5 S5 S6 A15
 N12 ->      12 (V:  1.99%) (N:  0.21%) PV: N12 A15 B15 S4 T4 T5 S5
26420 visits, 4015921 nodes, 26420 playouts, 528 n/s

= T4

undo
=

play white s4
=

genmove b
Thinking at most 50.0 seconds...
NN eval=0.906544
Playouts: 2031, Win: 95.75%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 3670, Win: 95.86%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 5452, Win: 95.92%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 6802, Win: 95.89%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 8717, Win: 95.90%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 10803, Win: 95.92%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 12863, Win: 95.94%, PV: A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
Playouts: 14561, Win: 95.95%, PV: A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 F6 D7 B19 C19
Playouts: 16426, Win: 95.95%, PV: A15 H4 J4 G4 F4 G6 D5 F6 C8 B8 D8 B15 G5 A16 B19 O19 Q19
Playouts: 19156, Win: 95.93%, PV: A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 F6 D7 B19 C19 A17
Playouts: 22883, Win: 95.93%, PV: A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 F6 D7 B19 C19 A17
Playouts: 25271, Win: 95.94%, PV: A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 F6 D7 B19 C19 A17 A19
Playouts: 27578, Win: 95.94%, PV: A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 F6 D7 B19 C19 A17 A19
Playouts: 29878, Win: 95.95%, PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 C5 G4
Playouts: 33282, Win: 95.92%, PV: A15 H4 J4 B15 B19 A16 C8 B8 D8 D5 E5 G6 G4 Q13 Q19 P19 N19 O19 G5 Q12
Playouts: 36716, Win: 95.92%, PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 C5 G4 F4
Playouts: 40626, Win: 95.92%, PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 G4 Q13 Q19 P19
Playouts: 44430, Win: 95.92%, PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 G4 Q13 Q19 P19
Playouts: 48347, Win: 95.92%, PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 G4 Q13 Q19 P19

 A15 ->   34747 (V: 96.09%) (N: 32.17%) PV: A15 H4 J4 B15 C8 B8 D8 A16 B19 D5 E5 G6 G4 Q13 Q19 P19
  C8 ->    6428 (V: 96.00%) (N:  8.90%) PV: C8 B8 D8 A15 B19 A17 A19 G5 D5 G4 F4 H4 J4 G6 F6 D7 C5
 B15 ->    3901 (V: 96.15%) (N:  2.02%) PV: B15 C15 A15 A16 C8 B8 D8 D5 E5 G5 G4 G6 H4 Q13 B19 Q12 P9 O19 Q19 N19
  D5 ->    1113 (V: 95.20%) (N:  6.35%) PV: D5 A15 C8 B8 D8 G5 G4 G6 F6 D7 H4 C5 B19 A17
  H4 ->    1052 (V: 95.50%) (N:  4.28%) PV: H4 A15 G5 G6 F6 D5 E5 D8 D7 C8 C5 Q13 Q19 P19 B19 A17 A19
  G5 ->     928 (V: 95.03%) (N:  6.17%) PV: G5 A15 H4 G6 D5 F6 C8 B8 D8 Q13 B19 Q12 P9 O19 Q19
 Q19 ->     907 (V: 95.56%) (N:  3.39%) PV: Q19 A15 B19 A17 A19 P19 C8 B8 D8 D5 E5 G5 G4 H4 J4
 B19 ->     656 (V: 95.54%) (N:  2.55%) PV: B19 A15 C8 B8 D8 A17 A19 D5 E5 G5 G4 H4 J4 G6 F6
 Q13 ->     487 (V: 95.28%) (N:  2.34%) PV: Q13 Q14 A15 B15 C8 B8 D8 D5 E5 G5 G4 G6 H4 F6
 A16 ->     217 (V: 95.75%) (N:  0.48%) PV: A16 A17 A15 B15 B19 A19 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9
 P19 ->     195 (V: 95.07%) (N:  1.22%) PV: P19 O19 Q19 A15 C8 B8 D8 D5 E5 G5 G4 H4 J4 Q13 P9 Q12
  D8 ->     191 (V: 95.45%) (N:  0.84%) PV: D8 C8 A15 B15 G5 G6 H4 D5 E5 A16 B19
  D7 ->     109 (V: 95.24%) (N:  0.61%) PV: D7 C8 A15 B15 D5 G5 G4 A16 B19 Q13
 O19 ->      87 (V: 94.17%) (N:  0.98%) PV: O19 P19 N19 A15 Q19 Q13 C8 B8 D8 D5 E5 G5 G4 H4
  G4 ->      78 (V: 94.88%) (N:  0.57%) PV: G4 A15 C8 B8 D8 D5 E5 G6 C5 Q13 Q19 P19 N19 Q12 P9 O19 H4 G5
 N19 ->      70 (V: 95.06%) (N:  0.45%) PV: N19 A15 A17 A16 B19 O19 Q19 Q13 C8 B8 D8 D5 E5 G5 G4 H4
 N12 ->      64 (V: 94.75%) (N:  0.53%) PV: N12 N13 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5 H4 G4 F4 G6
 A17 ->      59 (V: 94.40%) (N:  0.60%) PV: A17 A16 A15 B15 B19 G5 G4 D5 E5 D8 D7 C8
  C5 ->      49 (V: 94.34%) (N:  0.51%) PV: C5 A15 D5 G5 C8 B8 D8 Q13 G4 Q12
  K1 ->      38 (V: 88.89%) (N:  1.53%) PV: K1 A15 A17 A16 B19 G5 G4 D5 E5 C8 H4 G6 C5 Q13
 Q12 ->      36 (V: 92.14%) (N:  0.79%) PV: Q12 Q13 P9 A15 A17 A16 B19 O19 Q19 N19 C8 B8 D8 D5 E5 G5 G4 G6 H4
  P8 ->      33 (V: 93.62%) (N:  0.45%) PV: P8 A15 B19 A17 A19 G5 G4 D5 E5 C8 H4 G6
 S16 ->      31 (V: 94.22%) (N:  0.35%) PV: S16 A15 C8 B8 D8 D5 E5 G5 G4 O19 Q19 Q13
  E5 ->      30 (V: 94.30%) (N:  0.33%) PV: E5 A15 C8 B8 D8 G5 H4 G4 F4 G6 F6
  F4 ->      28 (V: 94.00%) (N:  0.33%) PV: F4 A15 A17 A16 B19 O19 Q19 Q13 C8 B8 D8 D5
 C19 ->      28 (V: 93.70%) (N:  0.38%) PV: C19 A15 A17 A16 G5 G6 H4 D5 E5 D8 D7 C8 C5
  F6 ->      25 (V: 94.45%) (N:  0.25%) PV: F6 A15 C8 B8 D8 D5 E5 G5 A17 A16 B19
  G6 ->      22 (V: 93.53%) (N:  0.31%) PV: G6 G5 F6 A15 G4 D5 E5 C8
 T16 ->      20 (V: 93.42%) (N:  0.24%) PV: T16 A15 A17 A16 B19 O19 Q19 Q13 C8 B8 D8 D5 E5 G5
  E4 ->      20 (V: 92.87%) (N:  0.28%) PV: E4 A15 B19 A17 A19 Q13 C8 B8 D8 Q12
  E1 ->      20 (V: 91.96%) (N:  0.43%) PV: E1 A15 A17 A16 B19 G5 G4 D5 E5 C8 H4 G6
 D19 ->      19 (V: 93.69%) (N:  0.27%) PV: D19 A15 A17 A16 B19 G5 D5 G4 F4 H4 J4 G6 F6
 A19 ->      19 (V: 93.23%) (N:  0.33%) PV: A19 B19 C19 A15 A19 A17 B19 D5 E5 G5
  P9 ->      19 (V: 92.64%) (N:  0.35%) PV: P9 A15 A17 A16 B19 D5 E5 G5 G4 Q13 H4 C8 C5 G6 F6 O19
  C2 ->      18 (V: 93.46%) (N:  0.29%) PV: C2 A15 A17 A16 B19 D5 E5 G5 G4 D8 D7 C8 C5 G6 H4
  G1 ->      15 (V: 93.66%) (N:  0.22%) PV: G1 A15 B19 A17 A19 Q13 C8 B8 D8 D5 E5 G5 G4
 Q14 ->      15 (V: 91.79%) (N:  0.37%) PV: Q14 Q13 A15 B15 Q12 Q15 P9 A16
 E19 ->      14 (V: 93.52%) (N:  0.20%) PV: E19 A15 C8 B8 D8 D5 E5 G5
 S17 ->      14 (V: 92.79%) (N:  0.27%) PV: S17 A15 C8 B8 D8 D5 E5 G5 G4 Q13 H4 Q12 P9 O19
  O3 ->      13 (V: 93.10%) (N:  0.24%) PV: O3 A15 G5 G6 H4 D5 E5 C8 C5
  T3 ->      13 (V: 92.44%) (N:  0.29%) PV: T3 T4 A15 B15 B19 A16 C8 B8 D8 D5 E5 G5
 T17 ->      12 (V: 93.43%) (N:  0.19%) PV: T17 A15 C8 B8 D8 D5 E5 G5 H4 G4 F4 G6
  M3 ->      12 (V: 92.79%) (N:  0.23%) PV: M3 A15 C8 B8 D8 D5 E5 G5 G4 Q13 H4 G6
 S18 ->      12 (V: 92.13%) (N:  0.29%) PV: S18 A15 A17 A16 C8 B8 D8 D5 E5 G5 G4 Q13
  J4 ->      12 (V: 91.58%) (N:  0.25%) PV: J4 A15 G5 G6 F6 D5 E5 C8 H4 Q13 C5 Q12
  N4 ->      11 (V: 93.01%) (N:  0.21%) PV: N4 A15 A17 A16 B19 Q13 G5 H4 J4 G6
 A10 ->      11 (V: 92.81%) (N:  0.16%) PV: A10 C8 A15 B15 D5 A16
  M2 ->      11 (V: 91.38%) (N:  0.21%) PV: M2 A15 G5 G6 H4 D5 E5 D8 D7 C8
  Q5 ->      10 (V: 93.03%) (N:  0.16%) PV: Q5 A15 A17 A16 B19 Q13 C8 B8 D8 D5
 F19 ->      10 (V: 92.94%) (N:  0.18%) PV: F19 A15 B19 A17 A19 G5 D5 D8 D7 C8
  N2 ->      10 (V: 92.54%) (N:  0.20%) PV: N2 A15 G5 G6 H4 D5 E5 D8
 D18 ->      10 (V: 92.17%) (N:  0.20%) PV: D18 A15 A17 A16 B19 Q13 G5 H4
  P5 ->      10 (V: 92.13%) (N:  0.24%) PV: P5 A15 C8 B8 D8 D5 E5 G5 G4 H4
  D3 ->      10 (V: 91.65%) (N:  0.21%) PV: D3 A15 A17 A16 B19 D5 E5 G5 G4 H4
  L1 ->      10 (V: 91.41%) (N:  0.27%) PV: L1 A15 A17 A16 B19 G5 D5 G4
 R19 ->      10 (V: 90.90%) (N:  0.28%) PV: R19 A15 A17 A16 C8 B8 D8 D5 E5 G5
  A1 ->       8 (V: 91.97%) (N:  0.20%) PV: A1 A15 C8 B8 D8 D5 E5 G5
  A3 ->       8 (V: 91.69%) (N:  0.17%) PV: A3 A15 A17 A16 B19 Q13 C8 B8
 T14 ->       8 (V: 91.37%) (N:  0.22%) PV: T14 A15 A17 A16 B19 Q13 C8 B8
 B10 ->       8 (V: 91.36%) (N:  0.16%) PV: B10 B9 A15 B15 G5
 T13 ->       8 (V: 91.26%) (N:  0.19%) PV: T13 A15 A17 A16 B19 G5 G4 D5
pass ->       8 (V: 91.09%) (N:  0.20%) PV: pass A15 A17 A16 B19 D5
 T15 ->       8 (V: 89.16%) (N:  0.16%) PV: T15 A15 A17 A16 B19 G5 D5 G4
  F1 ->       8 (V: 88.37%) (N:  0.26%) PV: F1 A15 A17 A16 B19 Q13 G5 H4
  O2 ->       7 (V: 88.33%) (N:  0.27%) PV: O2 A15 A17 A16 C8 B8
  M4 ->       6 (V: 91.34%) (N:  0.18%) PV: M4 A15 G5 H4 J4 G6
 G19 ->       6 (V: 91.23%) (N:  0.18%) PV: G19 A15 C8 B8 D8 D5
  M5 ->       6 (V: 91.19%) (N:  0.18%) PV: M5 A15 A17 A16 B19 G5
 T19 ->       6 (V: 90.77%) (N:  0.20%) PV: T19 A15 A17 A16 B19 D5
  L3 ->       6 (V: 90.70%) (N:  0.19%) PV: L3 A15 C8 B8 D8 D5
 T18 ->       6 (V: 90.44%) (N:  0.22%) PV: T18 A15 C8 B8 D8 D5
  K4 ->       6 (V: 90.43%) (N:  0.21%) PV: K4 A15 A17 A16 B19 D5
 S19 ->       6 (V: 88.27%) (N:  0.26%) PV: S19 A15 A17 A16 C8 B8
  L5 ->       6 (V: 88.17%) (N:  0.17%) PV: L5 A15 A17 A16 B19 Q13
  H1 ->       6 (V: 86.91%) (N:  0.28%) PV: H1 A15 A17 A16 C8 B8
  B8 ->       4 (V: 90.62%) (N:  0.15%) PV: B8 C8 A15 B15
  A2 ->       4 (V: 90.00%) (N:  0.17%) PV: A2 A15 A17 A16
  J8 ->       4 (V: 89.75%) (N:  0.17%) PV: J8 A15 A17 A16
 H19 ->       4 (V: 89.29%) (N:  0.19%) PV: H19 A15 A17 A16
  C3 ->       4 (V: 88.65%) (N:  0.18%) PV: C3 A15 C8 B8
  O4 ->       4 (V: 88.56%) (N:  0.15%) PV: O4 A15 A17 A16
  B9 ->       4 (V: 87.21%) (N:  0.18%) PV: B9 C8 A15 B15
  N5 ->       4 (V: 86.06%) (N:  0.19%) PV: N5 A15 C8 B8
  T5 ->       4 (V: 82.60%) (N:  0.16%) PV: T5 A15 A17 A16
  B6 ->       2 (V: 85.89%) (N:  0.17%) PV: B6 A15
  M1 ->       2 (V: 85.88%) (N:  0.17%) PV: M1 A15
  T4 ->       2 (V: 74.35%) (N:  0.18%) PV: T4 A15
52162 visits, 7836592 nodes, 52162 playouts, 1043 n/s

= A15

undo
=

undo
=

genmove w
Thinking at most 49.3 seconds...
NN eval=0.037356
Playouts: 28157, Win:  4.00%, PV: T4 A15 H4 J4 G4 F4 G6 D5 C8 F6 B15 B19 A16 G5 H8 A19
Playouts: 32943, Win:  4.01%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 36565, Win:  4.02%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 39875, Win:  4.04%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 43001, Win:  4.06%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 46123, Win:  4.03%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 48098, Win:  4.04%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 49939, Win:  4.04%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 52151, Win:  4.05%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 54204, Win:  4.05%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 56130, Win:  4.06%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 57347, Win:  4.06%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 59405, Win:  4.06%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 61141, Win:  4.07%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 62632, Win:  4.07%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 63974, Win:  4.07%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 65522, Win:  4.07%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 67423, Win:  4.08%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
Playouts: 69799, Win:  4.08%, PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19

  T4 ->   60166 (V:  4.36%) (N:  1.71%) PV: T4 A15 H4 J4 G4 F4 G6 B15 C15 C8 B8 D8 A16 D5 C5 F6 G5 B19 O19
 A15 ->    3704 (V:  0.83%) (N: 61.42%) PV: A15 S4 T4 T5 S5 T3 S3 S6 T2 T1 G5 G4 D5 E5 D8 D7 C8
  S3 ->    3326 (V:  4.35%) (N:  0.18%) PV: S3 A15 B15 C8 B8 D8 D5 E5 G5 G4 G6 H4 A16 B19 O19 Q19 Q13
  S4 ->     883 (V:  4.04%) (N:  1.33%) PV: S4 A15 B15 B19 A16 A19 A17 C8 B8 D8 D5 E5 G5 H4 Q13 G4
  D5 ->     338 (V:  2.48%) (N:  2.98%) PV: D5 E5 A15 S4 T4 T5 G5 G4 O19 Q19 D8 D7 C8 H4 G6 F6 C5
  G5 ->     285 (V:  1.92%) (N:  3.27%) PV: G5 S4 T4 T5 A15 D5 G4 F4 H4 J4 G6 F6 C8
  C8 ->     248 (V:  1.99%) (N:  2.77%) PV: C8 A15 B15 S4 T4 T5 S5 S6 A16 B19 G5
 O19 ->     229 (V:  2.13%) (N:  2.40%) PV: O19 A15 B15 S4 T4 T5 S5 S6 A16 B19 D5 E5 G5 G4 D8 D7 C8
  H4 ->     203 (V:  2.46%) (N:  1.82%) PV: H4 S4 T4 T5 A15 A17 A16 C8 B8 D8 D5 E5 O19 Q19
 B19 ->     183 (V:  2.28%) (N:  1.80%) PV: B19 C19 A15 S4 T4 T5 A17 A19 S5 T3 B19 C8 B8 D8
 Q13 ->     149 (V:  1.99%) (N:  1.67%) PV: Q13 A15 Q12 P9 B15 S4 T4 T5 S5 S6 A16 B19 O19 Q19 N19
 Q19 ->     130 (V:  2.30%) (N:  1.25%) PV: Q19 R19 A15 S4 T4 T5 S5 S6 P19 C8 B8 D8
  D8 ->     120 (V:  2.35%) (N:  1.13%) PV: D8 A15 B15 S4 T4 T5 S5 T3 S3 S6 T2
  G6 ->     109 (V:  2.42%) (N:  0.99%) PV: G6 A15 B15 S4 T4 T5 S5 T3 S3 S6 T2 T1
  D7 ->      93 (V:  2.59%) (N:  0.77%) PV: D7 S4 T4 T5 A15 D5 D8 G5 G6 H4 F6 E5
 S16 ->      92 (V:  2.96%) (N:  0.61%) PV: S16 S17 T16 T17 A15 S4 T4 T5 S5 S6 Q19 R19 P19
 P19 ->      68 (V:  2.09%) (N:  0.73%) PV: P19 A15 Q19 R19 B15 S4 T4 T5 S5 T3 S3 S6
  G4 ->      66 (V:  3.53%) (N:  0.25%) PV: G4 S4 T4 T5 S5 S6 A15 H4 G5 F4 O19 Q19 N19
  E5 ->      62 (V:  3.31%) (N:  0.31%) PV: E5 D5 G5 F6 A15 S4 T4 T5 S5 T3 S3
  F6 ->      61 (V:  3.73%) (N:  0.18%) PV: F6 A15 G6 E5 B15 S4 T4 T5 S5
  F4 ->      48 (V:  3.71%) (N:  0.13%) PV: F4 G5 A15 H4 D5 E5 G6 C8 B8
 D19 ->      41 (V:  3.63%) (N:  0.14%) PV: D19 D18 A15 S4 T4 T5 S5 T3 S3 S6 T2
 A17 ->      37 (V:  3.03%) (N:  0.23%) PV: A17 A15 B15 S4 T4 T5 S5 S6 B19
 A19 ->      36 (V:  2.92%) (N:  0.24%) PV: A19 A15 B15 B19 A17 S4 T4 T5 S5 T3
 T17 ->      34 (V:  3.65%) (N:  0.12%) PV: T17 S17 A15 S4 T4 T5 S5 T3 S3 S6
 T16 ->      28 (V:  3.34%) (N:  0.13%) PV: T16 S16 A15 S4 T4 T5 S5 T3 S3 S6 T2
 Q12 ->      28 (V:  2.79%) (N:  0.19%) PV: Q12 A15 Q13 P9 B15 S4 T4 T5 S5 S6 A16
  K1 ->      26 (V:  2.44%) (N:  0.23%) PV: K1 L1 A15 S4 T4 T5 S5 S6 O19 Q19 N19
 N19 ->      25 (V:  2.37%) (N:  0.23%) PV: N19 A15 B15 S4 T4 T5 S5 S6
  T3 ->      24 (V:  2.55%) (N:  0.19%) PV: T3 A15 B15 S4 T4 T5 S5 S6 A16
  C5 ->      23 (V:  2.54%) (N:  0.20%) PV: C5 D5 A15 S4 T4 T5 S5 T3 S3
  H1 ->      22 (V:  2.71%) (N:  0.16%) PV: H1 S4 T4 T5 A15 A17 A16 C8 B8 D8
  P8 ->      20 (V:  3.16%) (N:  0.11%) PV: P8 P9 A15 S4 T4 T5 S5 S6 D5 E5
  H8 ->      20 (V:  1.54%) (N:  0.27%) PV: H8 S4 T4 T5 S5 S6 A15
  L1 ->      19 (V:  3.01%) (N:  0.12%) PV: L1 S4 T4 T5 A15 A17 A16 B19 S5 S6
 A16 ->      18 (V:  2.55%) (N:  0.15%) PV: A16 A15 B15 S4 T4 T5 S5 T3 S3 S6
  O3 ->      17 (V:  2.95%) (N:  0.12%) PV: O3 O2 A15 S4 T4 T5 S5
  T2 ->      17 (V:  2.65%) (N:  0.14%) PV: T2 S4 T4 T5 S5 S6 S3 S5
  Q5 ->      16 (V:  2.26%) (N:  0.16%) PV: Q5 P5 A15 S4 T4 T5 S5 S6 G5
 B15 ->      16 (V:  1.98%) (N:  0.19%) PV: B15 S4 T4 T5 S5 T3 S3
 N12 ->      16 (V:  1.49%) (N:  0.21%) PV: N12 A15 B15 S4 T4 T5 S5 T3 S3
  B8 ->      14 (V:  2.02%) (N:  0.16%) PV: B8 A15 B15 S4 T4 T5 S5 T3 S3
 A10 ->      13 (V:  2.11%) (N:  0.14%) PV: A10 S4 T4 T5 A15 A17 A16
pass ->      13 (V:  1.81%) (N:  0.16%) PV: pass A15 B15 S4 T4 T5 S5 T3 S3
 N13 ->      12 (V:  2.28%) (N:  0.11%) PV: N13 A15 B15 S4 T4 T5 S5 T3
  E1 ->      12 (V:  2.22%) (N:  0.13%) PV: E1 A15 B15 S4 T4 T5 S5
  B9 ->      12 (V:  1.81%) (N:  0.14%) PV: B9 A15 B15 S4 T4 T5 S5
 N14 ->      11 (V:  2.41%) (N:  0.11%) PV: N14 S4 T4 T5 A15 B19
  B6 ->      11 (V:  2.15%) (N:  0.11%) PV: B6 A15 B15 S4 T4 T5 S5
 C19 ->      10 (V:  1.85%) (N:  0.12%) PV: C19 B19 A15 S4 T4 T5 S5
71154 visits, 10727670 nodes, 71154 playouts, 1443 n/s

= T4
```

**Comment by roy7** [comment]
@killerducky tells me double undo clears the tree now, so it makes both of my original complaints moot. I'll close the issue.
